server:
  port: 8088
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fenzi
    username: root
    password: 5678
mybatis-flex:
  mapper-locations: com.kangqing.teamcity.mapper/*.xml
  type-aliases-package: com.kangqing.teamcity.mapper